import Head from 'next/head';
import { Typography } from '@mui/material';
import MainLayout from '@/components/layouts/MainLayout';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout title='Open Jira'>
          <Typography
            variant="h1"
            color='primary'
          >
            Next app
          </Typography>
        </MainLayout>
      </main>
    </>
  )
}
